# Generated by Django 4.1.3 on 2022-11-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmanager', '0002_auto_20221123_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
